import json
import numpy as np
import matplotlib.pyplot as plt
import os

def analyze_discrepancy(data_file):
    if not os.path.exists(data_file):
        print(f"Error: {data_file} not found.")
        return

    with open(data_file, 'r') as f:
        data = json.load(f)

    aware_scores = np.array(data.get('aware', []))
    ignorant_scores = np.array(data.get('ignorant', []))

    print(f"\n==========================================================")
    print(f"DISCREPANCY SCORE STATISTICS")
    print(f"==========================================================")
    
    for label, scores in [("AWARE", aware_scores), ("IGNORANT", ignorant_scores)]:
        if len(scores) == 0:
            print(f"{label}: No data points collected.")
            continue
            
        print(f"{label} ({len(scores)} points):")
        print(f"  Mean:   {np.mean(scores):.4f}")
        print(f"  Median: {np.median(scores):.4f}")
        print(f"  StdDev: {np.std(scores):.4f}")
        print(f"  Min:    {np.min(scores):.4f}")
        print(f"  Max:    {np.max(scores):.4f}")
        print(f"  90th%:  {np.percentile(scores, 90):.4f}")
        print(f"  10th%:  {np.percentile(scores, 10):.4f}")
        print("-" * 30)

    # Plotting
    plt.figure(figsize=(12, 6))

    # Histogram
    plt.subplot(1, 2, 1)
    if len(aware_scores) > 0:
        plt.hist(aware_scores, bins=50, alpha=0.5, label='Aware', color='green', density=True)
    if len(ignorant_scores) > 0:
        plt.hist(ignorant_scores, bins=50, alpha=0.5, label='Ignorant', color='blue', density=True)
    plt.axvline(0, color='black', linestyle='--', alpha=0.5)
    plt.title("Discrepancy Score Distribution (Density)")
    plt.xlabel("Discrepancy Score (m)")
    plt.ylabel("Density")
    plt.legend()

    # Boxplot
    plt.subplot(1, 2, 2)
    box_data = []
    labels = []
    if len(aware_scores) > 0:
        box_data.append(aware_scores)
        labels.append('Aware')
    if len(ignorant_scores) > 0:
        box_data.append(ignorant_scores)
        labels.append('Ignorant')
    
    if box_data:
        plt.boxplot(box_data, labels=labels)
        plt.axhline(0, color='black', linestyle='--', alpha=0.5)
        plt.title("Discrepancy Score Boxplot")
        plt.ylabel("Discrepancy Score (m)")

    plt.tight_layout()
    os.makedirs("visualizations", exist_ok=True)
    save_path = "visualizations/discrepancy_analysis.png"
    plt.savefig(save_path)
    print(f"Analysis plot saved to {save_path}")
    print(f"==========================================================\n")

if __name__ == "__main__":
    # Path to the data generated by seperate_mixed_5050
    # Note: Adjust path if needed based on model directory
    model_name = "Ours_GST" # Default used in scripts
    data_file = f"trained_models/{model_name}/test/discrepancy_data_seperate_mixed_5050.json"
    analyze_discrepancy(data_file)
